name: Run tests

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd back-end
        pip install -r requirements.txt

    - name: Enable testing mode
      run: |
        cd back-end
        if [ -f .env ]; then
          sed -i 's/TESTING=False/TESTING=True/' .env
        else
          echo "TESTING=True" >> .env
        fi
        cat .env

    - name: Start FastAPI server in the background
      run: |
        cd back-end
        uvicorn app.app:app --reload &   

    - name: Run backend tests
      run: |
          cd back-end/app/tests
          pytest
